baseurl = "https://blog.z4hd.cf/"
copyright = '<a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/"><img alt="知识共享许可协议" style="border-width:0" src="https://global.cdn.mikupics.cn/2021/01/19/403632dac116d.png" /></a><br />如无特殊标注，则本文采用<a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/">知识共享署名-非商业性使用-相同方式共享 4.0 国际许可协议</a>进行许可。'
enableGitInfo = true
defaultContentLanguage = "zh-cn"
hasCJKLanguage = true
languageCode = "zh-CN"

title = "Z4HD's Blog"

theme = "LoveIt"

[author]
email = ""
link = "/"
name = "Z4HD"

[frontmatter]
lastmod = ["lastmod", "：git", ":fileModTime", ":default"]

# Config need by theme

[params]
# LoveIt 主题版本
version = "0.2.X"
defaultTheme = "dark"
# 描述
#description = "人活着就是为了死的"
fingerprint = "sha256"
#gitRepo = "https://github.com/Z4HD/z4hd-blog-hugo"

[params.social]
GitHub = "Z4HD"
RSS = true

[params.header]
# 桌面端导航栏模式 ("fixed", "normal", "auto")
desktopMode = "fixed"
# 移动端导航栏模式 ("fixed", "normal", "auto")
mobileMode = "auto"
# LoveIt 新增 | 0.2.0 页面头部导航栏标题配置
[params.header.title]
# LOGO 的 URL
#logo = "/favicon.ico"
# 标题名称
name = "Z4HD's BLOG"
# 你可以在名称 (允许 HTML 格式) 之前添加其他信息, 例如图标
#pre = ""
# 你可以在名称 (允许 HTML 格式) 之后添加其他信息, 例如图标
#post = ""
# LoveIt 新增 | 0.2.5 是否为标题显示打字机动画
typeit = true

[params.footer]
enable = true
# LoveIt 新增 | 0.2.0 自定义内容 (支持 HTML 格式)
custom = ''
# LoveIt 新增 | 0.2.0 是否显示 Hugo 和主题信息
hugo = true
# LoveIt 新增 | 0.2.0 是否显示版权信息
copyright = true
# LoveIt 新增 | 0.2.0 是否显示作者
author = true
license = '如无特殊标注，则本页面采用<a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/">知识共享署名-非商业性使用-相同方式共享 4.0 国际许可协议</a>进行许可。<br /><a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/"><img alt="知识共享许可协议" style="border-width:0" src="https://i.creativecommons.org/l/by-nc-sa/4.0/88x31.png" /></a>'
# 网站创立年份
since = 2017

[params.search]
enable = true
# 搜索引擎的类型 ("lunr", "algolia")
type = "lunr"
# 文章内容最长索引长度
contentLength = 4000
# 搜索框的占位提示语
placeholder = ""
# LoveIt 新增 | 0.2.1 最大结果数目
maxResultLength = 10
# LoveIt 新增 | 0.2.3 结果内容片段长度
snippetLength = 50
# LoveIt 新增 | 0.2.1 搜索结果中高亮部分的 HTML 标签
highlightTag = "em"
# LoveIt 新增 | 0.2.4 是否在搜索索引中使用基于 baseURL 的绝对路径
absoluteURL = false

[menu]
[[menu.main]]
identifier = "posts"
name = "所有文章"
# 你可以在名称 (允许 HTML 格式) 之前添加其他信息, 例如图标
pre = ""
# 你可以在名称 (允许 HTML 格式) 之后添加其他信息, 例如图标
post = ""
url = "/posts/"
# 当你将鼠标悬停在此菜单链接上时, 将显示的标题
title = ""
weight = 1
[[menu.main]]
identifier = "categories"
name = "分类"
post = ""
pre = ""
title = ""
url = "/categories/"
weight = 2
#[[menu.main]]
#identifier = "tags"
#name = "标签"
#post = ""
#pre = ""
#title = ""
#url = "/tags/"
#weight = 3

# Hugo 解析文档的配置
[markup]
# 语法高亮设置 (https://gohugo.io/content-management/syntax-highlighting)
[markup.highlight]
# false 是必要的设置 (https://github.com/dillonzq/LoveIt/issues/158)
noClasses = false

[outputs]
home = ["HTML", "RSS", "JSON"]
