[params]
[params.Midnight]
[params.Midnight.color]
    page_background = "#000000"
    main_background = "#050505"
    alt_background = "#252525"
    main_text = "#e2e2e2"
    alt_text = "#e2e2e2"
    accent = "#2c8cef"
    accent_text = "#e2e2e2"

[params.Midnight.comments]
    [params.Midnight.comments.commento]
    [params.Midnight.comments.commento.partial]
        path = "comments/commento/widget.html"
        cache = true
    [params.Midnight.comments.commento.foot]
        path = "comments/commento/foot.html"
        cache = true
    [params.Midnight.comments.commento.csp]
    [params.Midnight.comments.commento.csp.connect-src]
        path = "comments/commento/csp/script"
        cache = true
    [params.Midnight.comments.commento.csp.font-src]
        path = "comments/commento/csp/fonts"
        cache = true
    [params.Midnight.comments.commento.csp.script-src]
        path = "comments/commento/csp/script"
        cache = true
    [params.Midnight.comments.commento.csp.style-src]
        path = "comments/commento/csp/style"
        cache = true

[params.Midnight.fonts]
    header_style = "sans-serif"
    body_style = "sans-serif"
    print_header_style = "sans-serif"
    print_body_style = "serif"

[params.Midnight.shortcodes]
    [params.Midnight.shortcodes.handwriting]
        [params.Midnight.shortcodes.handwriting.head]
            path = "shortcodes/handwriting/head.html"
            cache = true
    [params.Midnight.shortcodes.math]
        [params.Midnight.shortcodes.math.head]
            path = "shortcodes/katex/head.html"
            cache = true
        [params.Midnight.shortcodes.math.foot]
            path = "shortcodes/katex/foot.html"
            cache = true
        [params.Midnight.shortcodes.math.csp]
        [params.Midnight.shortcodes.math.csp.font-src]
            path = "shortcodes/katex/csp/script"
            cache = true
        [params.Midnight.shortcodes.math.csp.script-src]
            path = "shortcodes/katex/csp/script"
            cache = true
        [params.Midnight.shortcodes.math.csp.style-src]
            path = "shortcodes/katex/csp/script"
            cache = true
    [params.Midnight.shortcodes.tabgroup]
        [params.Midnight.shortcodes.tabgroup.head]
            path = "shortcodes/tabgroup/head.html"
            cache = true
    [params.Midnight.shortcodes.table]
        [params.Midnight.shortcodes.table.head]
            path = "shortcodes/table/head.html"
            cache = true
    [params.Midnight.shortcodes.nebula-form]
        [params.Midnight.shortcodes.nebula-form.foot]
            path = "shortcodes/nebula-form/foot.html"
            cache = true
        [params.Midnight.shortcodes.nebula-form.csp]
        [params.Midnight.shortcodes.nebula-form.csp.connect-src]
            path = "shortcodes/forms/csp/connect"
    [params.Midnight.shortcodes.netlify-form]
        [params.Midnight.shortcodes.netlify-form.csp]
        [params.Midnight.shortcodes.netlify-form.csp.connect-src]
            path = "shortcodes/forms/csp/connect"
            cache = true


[params.Midnight.sidebar]
    [params.Midnight.sidebar.categories]
        [params.Midnight.sidebar.categories.partial]
            path = "sidebar/widgets/categories/widget.html"
            cache = true
    [params.Midnight.sidebar.patreon]
        [params.Midnight.sidebar.patreon.head]
            path = "sidebar/widgets/patreon/head.html"
            cache = true
        [params.Midnight.sidebar.patreon.partial]
            path = "sidebar/widgets/patreon/widget.html"
            cache = true
    [params.Midnight.sidebar.recent]
        [params.Midnight.sidebar.recent.partial]
            path = "sidebar/widgets/recent/widget.html"
    [params.Midnight.sidebar.search]
        [params.Midnight.sidebar.search.partial]
            path = "sidebar/widgets/search/widget.html"
            cache = true
        [params.Midnight.sidebar.search.foot]
            path = "sidebar/widgets/search/foot.html"
            cache = true
        [params.Midnight.sidebar.search.head]
            path = "sidebar/widgets/search/head.html"
            cache = true
        [params.Midnight.sidebar.search.csp]
        [params.Midnight.sidebar.search.csp.script-src]
            path = "sidebar/widgets/search/csp/script"
            cache = true
    [params.Midnight.sidebar.support]
        [params.Midnight.sidebar.support.partial]
            path = "sidebar/widgets/support/widget.html"
            cache = true
        [params.Midnight.sidebar.support.foot]
            path = "sidebar/widgets/support/foot.html"
            cache = true
        [params.Midnight.sidebar.support.head]
            path = "sidebar/widgets/support/head.html"
            cache = true
    [params.Midnight.sidebar.taglist]
        [params.Midnight.sidebar.taglist.head]
            path = "sidebar/widgets/taglist/head.html"
            cache = true
        [params.Midnight.sidebar.taglist.partial]
            path = "sidebar/widgets/taglist/widget.html"
            cache = true

[mediaTypes]
    [mediaTypes."netlify/headers"]
        suffixes = ["_headers"]
        delimiter = ""
    [mediaTypes."config/nginx"]
        suffixes = ["conf"]
    [mediaTypes."config/caddy"]
        suffixes = ["Caddyfile"]
        delimiter = ""

[outputFormats]
    [outputFormats.NetlifyHeaders]
        isPlainText = true
        basename = ""
        mediaType = "netlify/headers"
        notAlternative = true
    [outputFormats.nginx]
        isPlainText = true
        basename = "nginx"
        mediaType = "config/nginx"
        notAlternative = true
    [outputFormats.Caddyfile]
        isPlainText = true
        basename = ""
        mediaType = "config/caddy"
        notAlternative = true
